spring:
  application:
    name: oopbank
  datasource:
    url: jdbc:mysql://localhost:3306/oopbank_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  devtools:
    restart:
      enabled: true
